require('plugins')
--require('keys')
require('settings')
--require('utils')
require('language_providers')
require('lsp')
require('whichkey_lua')
vim.cmd("autocmd BufWritePost plugins.lua PackerCompile")
