require("core.plugins.cmp")
require("core.plugins.dashboard")
require("core.plugins.lspsaga")
require("core.plugins.lualine")
require("core.plugins.nvim_tree")
require("core.plugins.markdown_preview")
require("core.plugins.minimap")
require("core.plugins.presence")
require("core.plugins.searchbox")
require("core.plugins.transparent")
require("core.plugins.treesitter")
require("core.plugins.treesitter-playground")
require("core.plugins.trouble")
require("core.plugins.vim-slime")
require("core.plugins.bufferline")

